/**
 * @file agent/debug/types.ts
 * @description Type definitions and data contracts for Agent SDK Smart Debug Assistant.
 */

/**
 * Recommended next inspector action to run for deeper diagnostics.
 */
export interface NextInspectionRecommendation {
    /** Target inspector domain (e.g. "Tool Inspector", "Performance Inspector", "Behavior Advisor"). */
    target: string;
    /** Specific evidence-based reason for recommendation. */
    reason: string;
    /** Exact TypeScript command snippet to run for inspection. */
    command: string;
}

/**
 * Structured, evidence-based diagnostic report generated by Smart Debug Assistant.
 */
export interface DebugReport {
    /** Concise diagnostic summary of what happened. */
    summary: string;

    /** Array of detected anomalies or execution issues based strictly on empirical evidence. */
    detectedIssues: string[];

    /** Actionable optimization suggestions reused from Prompt & Behavior Advisors. */
    suggestions: string[];

    /** Specific recommended next inspectors to execute for deeper analysis. */
    nextInspections: NextInspectionRecommendation[];

    /** Short, educational developer tips explaining underlying model/SDK behaviors. */
    learningTips: string[];

    /** Critical warnings (e.g., retries, rate limits, tool loop warnings). */
    warnings: string[];

    /** Diagnostic confidence level based on available evidence. */
    confidence: "high" | "medium" | "low";
}

/**
 * Callable function signature for `result.debug()`, supporting `.markdown()` and `.json()` helpers.
 */
export interface DebugFunction {
    /** Prints a formatted diagnostic debug report directly to console.log(). */
    (): void;

    /** Returns formatted GitHub markdown debug report string. */
    markdown(): string;

    /** Returns the underlying structured DebugReport object. */
    json(): DebugReport;
}
